backend cicd

diff --git a/.github/workflows/backend.yml b/.github/workflows/backend.yml
--- a/.github/workflows/backend.yml
+++ b/.github/workflows/backend.yml
@@ -42,9 +42,6 @@ jobs:
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
 
-      - name: "Debug: Check image name"
-        run: "echo \"Image tag: $IMAGE_NAME:$DOCKER_TAG\""
-
       - name: Build Docker Image
         run: docker build -t $IMAGE_NAME:$DOCKER_TAG .
 
@@ -82,10 +79,21 @@ jobs:
 
       - name: "Debug: check downloaded files"
         run: |
+          echo "== Current Directory =="
+          pwd
+          echo "== ls -al =="
           ls -al
+          echo "== Check .env.local directory =="
           ls -al .env.local || echo "no .env.local found"
+          echo "== Check .env file =="
+          cat .env || echo ".env not found"
 
-      - name: Upload image and .env to server
+      - name: Recreate .env.local directory and move .env
+        run: |
+          mkdir -p .env.local
+          mv .env .env.local/.env
+
+      - name: Upload image and env to server
         uses: appleboy/scp-action@v0.1.5
         with:
           host: ${{ secrets.BE_HOST }}
